import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar"; // ✅ Check correct casing (NavBar → Navbar)
import AuthProvider from "@/app/utils/AuthProvider"; // ✅ Ensure correct path
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  console.log("Inter font className:", inter.className); // Debugging

  return (
    <html lang="en">
      <body className={inter?.className || ""}> {/* ✅ Ensure valid className */}
        <AuthProvider>
            <div className="bg-gradient-to-r from-gray-900 via-neutral-800 to-neutral-900 h-screen p-4 flex flex-col gap-2">
                 <div className="rounded-full bg-gradient-to-r from-gray-700 via-neutral-600 to-neutral-700"><Navbar/></div>
                 <div className="flex gap-2 flex-1">
                  <div className="m-5 w-[5%] rounded-full ">
                    <Sidebar/>
                  </div>
                  <div className=" m-5 w-[95%]">{children}</div>
                 </div>
            </div>
        </AuthProvider>
      </body>
    </html>
  );
}
