import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar"; // ✅ Check correct casing (NavBar → Navbar)
import Providers from "@/Provider"; // ✅ Ensure correct path
import AuthProvider from "@/app/utils/AuthProvider"; // ✅ Ensure correct path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  console.log("Inter font className:", inter.className); // Debugging

  return (
    <html lang="en">
      <body className={inter?.className || ""}> {/* ✅ Ensure valid className */}
        <AuthProvider>
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
            <Navbar />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
